version: 0.2 

phases: 
  pre_build: 
    commands: 
      - echo PRE_BUILD no tasks... 
  build: 
    commands: 
      - echo PRE_BUILD no tasks... 
  post_build: 
      commands: 
      - echo POST_BUILD Updating lambda Function... 
     
      # Account Dock
      - aws lambda update-function-code --function-name lambda-card --s3-bucket account-a-884069944685-codedeploy-artfacts --s3-key lambda-card/main.zip
